package service;

import javax.sql.rowset.serial.SerialException;
import javax.swing.table.TableColumn;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class TableCreate {
    private ConnectionClass con;

    private final String CREATE_TABLE_CLIENT = "CREATE TABLE Client (id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE, " +
            "name varchar(40), dateOfJoin Date, phoneNumber varchar(9), address varchar(30))";
    private final String CREATE_TABLE_GAME = "CREATE TABLE Game (id INTEGER GENERATED BY DEFAULT AS IDENTITY, "+
            "gameName varchar(40), manufacturer varchar(40), genre varchar(40), clientID INTEGER , FOREIGN KEY (clientID) REFERENCES Client(id))";
    public TableCreate(ConnectionClass con) {
        this.con = con;
        try {
            ResultSet rs = this.con.getCon().getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;

            while (rs.next()) {
                if ("Client".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }
            if (!tableExists) {
                PreparedStatement createClientTablePST = this.con.getCon().prepareStatement(CREATE_TABLE_CLIENT);
                createClientTablePST.executeUpdate();
            }

            ResultSet rs2 = this.con.getCon().getMetaData().getTables(null, null, null, null);
            boolean tableExists2 = false;

            while (rs2.next()) {
                if ("Game".equalsIgnoreCase(rs2.getString("TABLE_NAME"))) {
                    tableExists2 = true;
                    break;
                }
            }
            if (!tableExists2) {
                PreparedStatement createClientTablePST = this.con.getCon().prepareStatement(CREATE_TABLE_GAME);
                createClientTablePST.executeUpdate();
            }
        }
        catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
